//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Editora
    {
        public Editora()
        {
            this.Livro = new HashSet<Livro>();
        }

        public int IdEditora { get; set; }
        [Required(ErrorMessage = "O nome da editora é obrigatório!", AllowEmptyStrings = false)]
        public string NomeEditora { get; set; }
        [Required(ErrorMessage = "O telefone da editora é obrigatório!", AllowEmptyStrings = false)]
        public string TelefoneEditora { get; set; }

        public virtual ICollection<Livro> Livro { get; set; }
    }
}
