//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LivrariaModelContainer : DbContext
    {
        public LivrariaModelContainer()
            : base("name=LivrariaModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Editora> Editora { get; set; }
        public virtual DbSet<Livro> Livro { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
    }
}
