//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedido
    {
        public Pedido()
        {
            this.Item = new HashSet<Item>();
        }
        
        public int IdPedido { get; set; }
        
        public int IdCliente { get; set; }
        [Required(ErrorMessage = "A data é obrigatório!", AllowEmptyStrings = false)]
        public System.DateTime DataPedido { get; set; }
        [Required(ErrorMessage = "O valor é obrigatório!", AllowEmptyStrings = false)]
        public double ValorPedido { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
